import type { Metadata } from "next";
import { /*Geist, Geist_Mono,*/ Exo_2 } from "next/font/google";
import "./styles/globals.css";
/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
const exo2 = Exo_2({
  variable: "--font-exo2",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Nacherdev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo2.variable} ${exo2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
